test39

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -18,7 +18,7 @@ env:
   AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  CONTAINER_IMAGE: ${{ github.sha }}
+  CONTAINER_IMAGE: example-eks:latest
 jobs:
   build-and-push:
     name: Build and deploy
@@ -33,11 +33,12 @@ jobs:
     - name: Setup ECR
       run: |
         # Login to AWS ECR
-         aws ecr get-login-password --region us-east-1 | sed 's|https://||'
+        # aws ecr get-login-password --region us-east-1 | sed 's|https://||'
+         $(aws ecr get-login --no-include-email --region $AWS_REGION | sed 's/-e none//') || error "AWS ECR Login Failed"
     - name: Build, tag, and push image to Amazon ECR
       run: |
         # Build and tag the image
         docker build \
           -t $CONTAINER_IMAGE \
-          -t 074002960123.dkr.ecr.us-east-1.amazonaws.com/example-eks/$CONTAINER_IMAGE ./app
-        docker push 074002960123.dkr.ecr.us-east-1.amazonaws.com/example-eks/$CONTAINER_IMAGE
+          -t 074002960123.dkr.ecr.us-east-1.amazonaws.com/$CONTAINER_IMAGE ./app
+        docker push 074002960123.dkr.ecr.us-east-1.amazonaws.com/$CONTAINER_IMAGE
